version: "3.1"
services:

    frontend:
      container_name: affald-frontend
      build:
        context: .
        dockerfile: Docker/Frontend/Dockerfile
      working_dir: /code
      ports:
        - "80:3000"
      volumes:
#        - ./frontend/src:/code/src
        - ./frontend/public:/code/public
    api:
      container_name: affald-api
      build:
        context: .
        dockerfile: Docker/API/Dockerfile
      working_dir: /code
      ports:
        - "5000:5000"
      volumes:
        - ./api/src:/code/src
