version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: affald-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=affald
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
    frontend:
      container_name: affald-frontend
      build:
        context: .
        dockerfile: Docker/Frontend/Dockerfile
      working_dir: /code
      ports:
        - "80:3000"
      volumes:
        - ./api/src:/code/src
        - ./api/public:/code/public
    api:
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=affald
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
      container_name: affald-api
      build:
        context: .
        dockerfile: Docker/API/Dockerfile
      working_dir: /code
      ports:
        - "3000:3000"
      volumes:
        - ./api/src:/code/src